version: 2

sources:
  - name: bitcoin_cash
    database: bigquery-public-data
    schema: crypto_bitcoin_cash
    tables:
      - name: transactions
        description: "Raw Bitcoin Cash transactions data"
        columns:
          - name: "`hash`"
            description: "The hash of this transaction"
            tests:
              - not_null
          - name: size
            description: "The size of this transaction in bytes"
          - name: virtual_size
            description: "The virtual transaction size (differs from size for witness transactions)"
          - name: version
            description: "Protocol version specified in block which contained this transaction"
          - name: lock_time
            description: "Earliest time that miners can include the transaction"
          - name: block_hash
            description: "Hash of the block which contains this transaction"
            tests:
              - not_null
          - name: block_number
            description: "Number of the block which contains this transaction"
            tests:
              - not_null
          - name: block_timestamp
            description: "Timestamp of the block which contains this transaction"
            tests:
              - not_null
          - name: block_timestamp_month
            description: "Month of the block which contains this transaction"
            tests:
              - not_null
          - name: input_count
            description: "The number of inputs in the transaction"
          - name: output_count
            description: "The number of outputs in the transaction"
          - name: input_value
            description: "Total value of inputs in the transaction"
          - name: output_value
            description: "Total value of outputs in the transaction"
          - name: is_coinbase
            description: "true if this transaction is a coinbase transaction"
          - name: fee
            description: "The fee paid by this transaction"
          - name: inputs
            description: "Transaction inputs"
          - name: outputs
            description: "Transaction outputs"


models:
  - name: STG_Table_Transactions_3M
    description: "Staging table for Bitcoin Cash transactions from the last 3 months"
    columns:
      - name: "`hash`"
        description: "The unique hash of the transaction"
        tests:
          - unique
          - not_null

      - name: block_hash
        description: "Hash of the block containing this transaction"
        tests:
          - not_null

      - name: block_number
        description: "Block number containing this transaction"
        tests:
          - not_null
          
      - name: block_timestamp
        description: "Timestamp of the block containing this transaction"
        tests:
          - not_null

      - name: block_timestamp_month
        description: "Month of the block containing this transaction"
        tests:
          - not_null