version: 2

models:
  - name: DMT_Adresses_Balance
    description: "Aggregated balances for addresses (excluding coinbase) over the last 3 months."
    columns:
      - name: address
        description: "Unique address identifier."
        tests:
          - not_null
          - unique
      - name: block_timestamp_month
        description: "Month of the block timestamp."
        tests:
          - not_null
      - name: first_activity
        description: "Earliest known block timestamp for this address."
        tests:
          - not_null
      - name: last_activity
        description: "Most recent block timestamp for this address."
        tests:
          - not_null