name: DBT CI

on:
  pull_request:
  # push:
  #   branches: [main, master]

jobs:
  dbt:
    runs-on: ubuntu-latest
    permissions:
      contents: write 

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Google auth to authenticate with BigQuery
      - name: Google Auth
        id: auth
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }} 
          export_environment_variables: true  # Exporting so that dbt can use it
     
          
      - name: Create profiles.yml with OAuth method
        run: |
          mkdir -p ~/.dbt
          cat > ~/.dbt/profiles.yml << EOF
          bitcoin_cash:
            target: ci
            outputs:
              ci:
                type: bigquery
                method: oauth
                project: ${{ vars.GCP_PROJECT_ID }}
                dataset: ${{ vars.GCP_DATASET_ID }}
                location: US
                threads: 4
      
      
      - name: Debug DBT 
        run: dbt debug

      - name: Run DBT
        run: dbt run
      
      - name: Test DBT 
        run: dbt test
      
      - name: Generate dbt docs
        run: dbt docs generate

        
      # Deploying dbt docs to GitHub Pages
      - name: Deploy dbt docs to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: target  
          branch: gh-pages
          clean: true  # To automatically remove deleted files from the deploy branch